version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: mongodb_migration
    ports:
      - "27020:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=source_db

  postgres:
    image: postgres:15
    container_name: postgres_migration
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=target_db
    
volumes:
  mongo_data:
  postgres_data: 